---
- name: Install Org Runner
  user: ansible
  hosts: all
  become: yes
  vars:
    - runner_user: ansible
    - github_account: monolithprojects-testorg
    - runner_org: yes
    - runner_state: "stopped"
    - runner_version: "2.287.0"
  roles:
    - robertdebock.epel
    - ansible-github_actions_runner
