---
 # ansible-galaxy install -f -r ./requirements.yml --roles-path=./code/ansible/roles

- name: geerlingguy.docker
  version: master

- name: geerlingguy.pip
  version: master

- name: monolithprojects.github_actions_runner
  version: master

- name: monolithprojects.user_management
  version: master