---
# ansible-galaxy install -f -r ./requirements.yml --roles-path=./code/ansible/roles

- name: geerlingguy.docker
  version: master

- name: geerlingguy.pip
  version: master

- name: monolithprojects.github_actions_runner
  version: 1.18.3

- name: monolithprojects.user_management
  version: master

- name: monolithprojects.homeassistant_compliance
  version: 0.1.1