############ Deploy Infra #######################

- name: Deploy Infrastructure
  import_playbook: code/ansible/playbooks/infra.yml
  tags: 
    - deploy
    - infra

############ Bootstrap VMs ######################

- name: Bootstrap all nodes
  import_playbook: code/ansible/playbooks/bootstrap.yml
  tags: 
    - deploy
    - bootstrap

############ Bootstrap VMs ######################

- name: Hassio prerequisites
  import_playbook: code/ansible/playbooks/homeassistant.yml
  tags: 
    - deploy
    - hassio
    - bootstrap

# ########### Install Runners ####################

- name: Install Runners
  import_playbook: code/ansible/playbooks/runner.yml
  tags: 
    - deploy
    - runner
    - runners

############ Prepare backup #####################

- name: Prepare backup
  import_playbook: code/ansible/playbooks/backup.yml
  tags: 
    - deploy
    - backup