############ Deploy Infra #######################

- name: Deploy Infrastructure
  import_playbook: code/ansible/playbooks/infra.yml
  tags: 
    - deploy
    - infra

############ Bootstrap VMs ######################

- name: Bootstrap all nodes
  import_playbook: code/ansible/playbooks/bootstrap.yml
  tags: 
    - deploy
    - bootstrap


############ Install Runners ####################

- name: Install Runners
  import_playbook: code/ansible/playbooks/runner.yml
  tags: 
    - deploy
    - runner
    - runners