---
- name: systemd reload
  become: yes
  systemd:
    daemon_reload: yes

- name: docker restart
  become: yes
  systemd:
    name: docker
    state: restarted

- name: systemd-resolved restart
  become: yes
  systemd:
    name: systemd-resolved
    state: restarted

- name: Update grub
  command: update-grub
  become: yes

- name: reboot server
  reboot:
  listen: Update grub