---

- name: Home-Assistant node prerequisites
  hosts: hassio
  user: sshadmin
  become: yes
  gather_facts: yes
  vars:
    ha_fix_network_manager: no

  roles:
    - monolithprojects.homeassistant_compliance
