---
- block:
  - name: Set complete API url for repo runner
    set_fact:
      github_full_api_url: "{{ github_api_url }}/repos/{{ github_owner | default(github_account) }}/{{ github_repo }}/actions/runners"
    when: not runner_org

  - name: Set complete API url for org runner
    set_fact:
      github_full_api_url: "{{ github_api_url }}/orgs/{{ github_owner | default(github_account) }}/actions/runners"
    when: runner_org | bool

  - name: Get registration token (RUN ONCE)
    uri:
      url: "{{ github_full_api_url }}/registration-token"
      headers:
        Authorization: "token {{ access_token }}"
        Accept: "application/vnd.github.v3+json"
      method: POST
      status_code: 201
      force_basic_auth: yes
    register: registration
    run_once: yes

  - name: Check currently registered runners for repo (RUN ONCE)
    uri:
      url: "{{ github_full_api_url }}"
      headers:
        Authorization: "token {{ access_token }}"
        Accept: "application/vnd.github.v3+json"
      method: GET
      status_code: 200
      force_basic_auth: yes
    register: registered_runners
    run_once: yes

  - name: Check service facts
    service_facts:

  check_mode: false
