# Ansible group vars for all nodes

# Environment name (infotunatelly can not use inventory_dir variable for local run)
system_env: prod

# Pip packages to be deployed on vServer(s)
pip_install_packages:
  - docker

data_disk: sda1
backup_disk: sdb1

run_backup: false
