---
- name: NetworkManager restart
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Update grub
  ansible.builtin.command: update-grub

- name: Reboot server
  ansible.builtin.reboot:
  listen: Update grub
